version: '3.9'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    networks:
      - devnet

  jenkins:
    build:
      context: ../jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - devnet
    volumes:
      - jenkins_home:/var/jenkins_home   # 🔑 volumen administrado por Docker
      - /var/run/docker.sock:/var/run/docker.sock

  nexus:
    image: sonatype/nexus3
    container_name: nexus_repo
    ports:
      - "8081-8083:8081-8083"
    networks:
      - devnet

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "8084:9000"
    networks:
      - devnet
    depends_on:
      - db_sonar

  db_sonar:
    image: postgres:15
    container_name: db_sonar
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    networks:
      - devnet

networks:
  devnet:

volumes:
  jenkins_home:   # 🔑 aquí definimos el volumen persistente de Jenkins
  nexus-data:
  postgresql:
  postgresql_data: